apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
stringData:
  application-secret.yaml: |
    spring:
      datasource:
        username: {{ .Values.spring.datasource.username }}
        password: {{ .Values.spring.datasource.password }}

      kakao:
        client-id: {{ .Values.spring.kakao.clientId }}
        client-secret: {{ .Values.spring.kakao.clientSecret}}
    jwt:
      secret-key: {{ .Values.jwt.secretKey}}