replicaCount: 1
image:
  repository: (censored).dkr.ecr.ap-northeast-2.amazonaws.com/backend_asset
  tag: "0.11.1"
  pullPolicy: Always
service:
  port: 8082
containerPort: 8082
env:
  profiles: prod
spring:
  kafka:
    listener:
      ackMode: manual_immediate
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      enableAutoCommit: false
      autoOffsetReset: latest
      maxPollRecords: 10
      properties:
        springJsonTrustedPackages: \"*\"
        springJsonUseTypeHeaders: false
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        springJsonAddTypeHeaders: false
    bootstrapServers: (censored):9092 # 매일 갈아줄 필요
  datasource:
    url: jdbc:mariadb://cloud-rds.(censored).ap-northeast-2.rds.amazonaws.com:3306/asset?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: admin123!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTestQuery: SELECT 1
      validationTimeout: 5000
  jpa:
    hibernate:
      ddlAuto: none
    generateDdl: true
    showSql: true
    openInView: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
escrow:
  baseUrl: http://backend-escrow-service:8084
market:
  baseUrl: http://backend-market-service:8086
ENCRYPTION_MASTER_KEY: (censored)
