apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.profiles }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-configmap
            items:
            - key: application-{{ .Values.env.profiles }}.yaml
              path: application-{{ .Values.env.profiles }}.yaml
        - name: secret-volume
          secret:
            secretName: {{ .Chart.Name }}-secret
            items:
            - key: application-secret.yaml
              path: application-secret.yaml
