apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  application-{{ .Values.env.profiles }}.yaml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: backend-user
                uri: http://backend-user-service:8081
                predicates:
                  - Path=/api/user/**
                filters:
                  - addAuthenticationHeader

              - id: backend-asset
                uri: http://backend-asset-service:8082
                predicates:
                  - Path=/api/asset/**
                filters:
                  - addAuthenticationHeader

              - id: backend-product
                uri: http://backend-product-service:8083
                predicates:
                  - Path=/api/product/**
                filters:
                  - addAuthenticationHeader

              - id: backend-escrow
                uri: http://backend-escrow-service:8084
                predicates:
                  - Path=/api/escrow/**
                filters:
                  - addAuthenticationHeader

              - id: backend-blockchain-connector
                uri: http://backend-blockchain-connector-service:8085
                predicates:
                  - Path=/api/contract/**
                filters:
                  - addAuthenticationHeader

              - id: backend-market
                uri: http://backend-market-service:8086
                predicates:
                  - Path=/api/market/**
                filters:
                  - addAuthenticationHeader

              - id: backend-notification
                uri: http://backend-notification-service:8087
                predicates:
                  - Path=/api/notification/**
                filters:
                  - addAuthenticationHeader

              - id: backend-kyc
                uri: http://backend-kyc-service:8088
                predicates:
                  - Path=/api/kyc/**
                filters:
                  - addAuthenticationHeader

              - id: backend-monitoring
                uri: http://backend-monitoring-service:8089
                predicates:
                  - Path=/api/monitoring/**
                filters:
                  - addAuthenticationHeader    
          httpclient:
            connect-timeout: 10000
            response-timeout: 5m
    jwt:
      header: Authorization
